import { test, expect, type Page } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
const admin = createClient(process.env.E2E_SUPABASE_URL!, process.env.E2E_SUPABASE_ADMIN_KEY!, { auth: { persistSession: false } });
const email = `report-${randomUUID()}@example.test`;
const password = randomUUID();
let userId: string;
let workspaceId: string;
let challengeId: string;
async function login(page: Page) {
  await page.goto("/login");
  await page.getByLabel("Team email").fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Open team workspace" }).click();
  await expect(page.getByRole("heading", { name: "Report team" })).toBeVisible();
}
test.beforeAll(async () => {
  const { data, error } = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (error) throw error;
  userId = data.user.id;
  const { data: workspace, error: workspaceError } = await admin.from("workspaces").insert({ owner_id: userId, name: "Report team" }).select("id").single();
  if (workspaceError) throw workspaceError;
  workspaceId = workspace.id;
});
test.afterAll(async () => {
  if (!userId) return;
  const { data: files } = await admin.storage.from("evidence").list(`${workspaceId}/${challengeId}`);
  if (files?.length) await admin.storage.from("evidence").remove(files.map(file => `${workspaceId}/${challengeId}/${file.name}`));
  const { error } = await admin.auth.admin.deleteUser(userId);
  if (error) throw error;
});
test("manual write-up becomes a reviewed, downloadable, immutable PDF report", async ({ page }) => {
  test.setTimeout(120_000);
  await login(page);
  await page.getByLabel("Competition name").fill("Practice CTF");
  await page.getByRole("button", { name: "Create competition" }).click();
  await expect(page).toHaveURL(/\/dashboard\/competitions\/[0-9a-f-]+$/);
  const competitionId = new URL(page.url()).pathname.split("/").at(-1)!;
  await page.getByLabel("Challenge name").fill("Hidden image");
  await page.getByRole("button", { name: "Add challenge" }).click();
  await expect(page).toHaveURL(/\/dashboard\/competitions\/[0-9a-f-]+\/challenges\/[0-9a-f-]+$/);
  challengeId = new URL(page.url()).pathname.split("/").at(-1)!;
  await page.getByLabel("Challenge prompt or description").fill("Find the flag in the provided image.");
  await page.getByLabel("Flag (optional)").fill("CTF{manual-report}");
  await expect(page.getByRole("status")).toContainText("Saved", { timeout: 20_000 });
  const image = await page.screenshot();
  await page.getByLabel("Choose screenshots").setInputFiles({ name: "evidence.png", mimeType: "image/png", buffer: image });
  await expect(page.getByText("Screenshots 1")).toBeVisible();
  await page.getByRole("link", { name: /Edit write-up/ }).click();
  await expect(page.getByLabel("Challenge overview content")).toContainText("Find the flag");
  await page.getByRole("navigation", { name: "Write-up sections" }).getByRole("button", { name: /Solution steps/ }).click();
  await page.getByLabel("Solution steps content").fill("1. Inspect the file metadata.\n2. Run `exiftool evidence.png`.\n\n```bash\nexiftool evidence.png\n```\n\nThe comment field revealed the flag.");
  await page.getByRole("checkbox", { name: "Screenshot" }).check();
  await page.getByRole("navigation", { name: "Write-up sections" }).getByRole("button", { name: /Flag recovery and result/ }).click();
  await expect(page.getByLabel("Flag recovery and result content")).toContainText("CTF{manual-report}");
  await page.getByRole("button", { name: "Approve write-up" }).click();
  await expect(page.getByRole("status")).toContainText("Reviewed", { timeout: 20_000 });
  await page.goto(`/dashboard/competitions/${competitionId}/reports`);
  await expect(page.getByRole("heading", { name: "Choose challenges" })).toBeVisible();
  await expect(page.getByText("Needs review")).toHaveCount(0);
  await page.getByRole("button", { name: "Save report snapshot" }).click();
  await expect(page).toHaveURL(/\/reports\/[0-9a-f-]+$/);
  await expect(page.getByRole("heading", { name: "Practice CTF" })).toBeVisible();
  const reportUrl = page.url();
  const downloadPromise = page.waitForEvent("download", { timeout: 90_000 });
  await page.getByRole("button", { name: "Download PDF" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("practice-ctf-report.pdf");
  const path = await download.path();
  expect(path).toBeTruthy();
  const text = execFileSync("pdftotext", [path!, "-"], { encoding: "utf8" });
  expect(text).toContain("Practice CTF");
  expect(text).toContain("Hidden image");
  expect(text).toContain("CTF{manual-report}");
  expect(text).toContain("exiftool evidence.png");
  const images = execFileSync("pdfimages", ["-list", path!], { encoding: "utf8" });
  expect(images.split("\n").length).toBeGreaterThan(2);
  await page.goto(`/dashboard/competitions/${competitionId}/challenges/${challengeId}`);
  page.on("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Remove" }).click();
  await expect(page.getByText("Screenshots 0")).toBeVisible();
  await page.getByLabel("How we solved it").fill("A later correction to the original notes.");
  await expect(page.getByRole("status")).toContainText("Saved", { timeout: 20_000 });
  await page.goto(`/dashboard/competitions/${competitionId}/reports`);
  await expect(page.getByText("Needs review")).toBeVisible();
  await expect(page.getByRole("button", { name: "Save report snapshot" })).toBeDisabled();
  await page.goto(reportUrl);
  await expect(page.getByText("exiftool evidence.png").first()).toBeVisible();
  await expect(page.getByRole("img", { name: "Challenge screenshot" })).toBeVisible();
});
